title: AyokaACR's Statuspage
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.ayokaacr.net
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Website
      description: The web frontend for Ayokas Stuff.
      category: Uncategorized
      link: https://ayokaacr.net/
    - name: AyokaRadio
      category: Uncategorized
      link: https://radio.ayokaacr.net/
    - name: Pastebin
      category: Uncategorized
      link: https://paste.ayokaacr.net/
    - name: Jenkins
      category: Uncategorized
      link: https://ci.ayokaacr.net
    - name: Download Page
      category: Uncategorized
      link: https://dl.ayokaacr.net
    - name: Telegram Uno Bot
      category: Telegram Stuff
      link: https://t.me/AyokaUnoBot
    - name: droid-ng Bot
      category: Telegram Stuff
      link: https://t.me/droid_ng
  dateFormat: January 2, 2006 at 15:04 UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  customTabs: []
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: monthly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Uncategorized
      untitled: true
    - name: Telegram Stuff
      description: Just some unimportant stuff
      closed: true
  description: Hey there and welcome to AyokaACR's Statuspage. You can check those
    statuses 24/7 thanks to GitLab hosting it for us.
  enableCustomHTML: true
  useLargeHeaderDesign: false
